from __future__ import annotations
from typing import Protocol

class FeatureFlags(Protocol):
    def is_enabled(self, name: str) -> bool: ...
    def set(self, name: str, value: bool) -> None: ...
    def all(self) -> dict[str, bool]: ...
