from __future__ import annotations
from typing import Protocol

class SecretsVault(Protocol):
    def put(self, name: str, value: str) -> None: ...
    def get(self, name: str) -> str | None: ...
    def delete(self, name: str) -> None: ...
    def list(self, prefix: str = "") -> list[str]: ...
